output_dir: "exps/cdutl"
true_gpu: "4"
gpu: [0]
random_seed: 0
auto_resume: True
master_port: "11327"
model_file: "gbinet_clean"
model_name: "GBiNet"
test_func_name: "test_model_stage_profile"
dataset: "general_eval"
max_depth: 8
model_path: "checkpoints/model_019.ckpt"
img_mean: [0.5, 0.5, 0.5]
img_std: [0.5, 0.5, 0.5]
sam_img_size: 1024

model:
  is_stage: True
  stage_num: 4
  output_channels: [64, 32, 16, 8]
  group_nums: [8, 8, 8, 4]
  feat_name: "SC_StageNet1"
  use_3dbn: True
  stage_info:
    scale:
      "0": 0.125
      "1": 0.25
      "2": 0.5
      "3": 1.0
    depth2stage:
      "1": 0
      "2": 0
      "3": 1
      "4": 1
      "5": 2
      "6": 2
      "7": 3
      "8": 3
      "9": 3 # needed and invalid, just for checking

test:
  batch_size: 1
  log_period: 10
  test_metric: "thres2mm_accu"

data:
  num_workers: 4
  test:
    root_dir: "/home/d6813/LZHL/blended_large"
    num_view: 9
    interval_scale: 0.8
    num_depth: 64
    listfile:  "lists/custom/all.txt"
    out_scale: 1.0
    self_norm: False
    color_mode: null
    with_gt: False
    max_h: null
    max_w: null
    base_image_size: 64
    is_clean: True
    out_depths: [8]
    prob_out_depths: [1, 2, 3, 4, 5, 6, 7, 8]
    save_depths: [8]
    prob_depth: 7

#no_testing: True
# no_fusion: True

fusion:
  name: "xy_filter_per"
  xy_filter_per:
    nprocs: 1
    global_pair: False
    para_num: 1
    para_tag: [0]
    output_dir: "exps/cdutl"
    scan1:
      prob_threshold: [0.7]
      num_consistent: [3]
      img_dist_thresh: [1]
      depth_thresh: [0.005]
#    scan3:
#      prob_threshold: [0.8]
#      num_consistent: [3]
#      img_dist_thresh: [1]
#      depth_thresh: [0.005]
#    scan11:
#      prob_threshold: [0.8]
#      num_consistent: [3]
#      img_dist_thresh: [1]
#      depth_thresh: [0.005]
#    scan32:
#      prob_threshold: [0.8]
#      num_consistent: [3]
#      img_dist_thresh: [1]
#      depth_thresh: [0.005]
#    scan59:
#      prob_threshold: [0.8]
#      num_consistent: [3]
#      img_dist_thresh: [1]
#      depth_thresh: [0.005]